//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Vue.Language {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Console_Vue.Language.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Traditional Chinese.
        /// </summary>
        internal static string CHT {
            get {
                return ResourceManager.GetString("CHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à German.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [] Leave blank to cancel and return to main menu.
        /// </summary>
        internal static string Default_back {
            get {
                return ResourceManager.GetString("Default_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have chosen to cancel and return to the main menu..
        /// </summary>
        internal static string Default_back2 {
            get {
                return ResourceManager.GetString("Default_back2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chosed, to get the default path.
        /// </summary>
        internal static string Default_default {
            get {
                return ResourceManager.GetString("Default_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chosed {0} as default log file type.
        /// </summary>
        internal static string Default_log_back {
            get {
                return ResourceManager.GetString("Default_log_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] json.
        /// </summary>
        internal static string Default_log_opt1 {
            get {
                return ResourceManager.GetString("Default_log_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] XML.
        /// </summary>
        internal static string Default_log_opt2 {
            get {
                return ResourceManager.GetString("Default_log_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What type of file do you want as log files ?.
        /// </summary>
        internal static string Default_log_question {
            get {
                return ResourceManager.GetString("Default_log_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chosed to set a new app path, wich is : .
        /// </summary>
        internal static string Default_New {
            get {
                return ResourceManager.GetString("Default_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] Enter the path for the new location.
        /// </summary>
        internal static string Default_opt1 {
            get {
                return ResourceManager.GetString("Default_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [D] To use the default location.
        /// </summary>
        internal static string Default_opt2 {
            get {
                return ResourceManager.GetString("Default_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to change the default app files location.
        /// </summary>
        internal static string Default_question {
            get {
                return ResourceManager.GetString("Default_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [] Leave blank to cancel and return to main menu.
        /// </summary>
        internal static string Display_back {
            get {
                return ResourceManager.GetString("Display_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press return to go back to the main menu....
        /// </summary>
        internal static string Display_back2 {
            get {
                return ResourceManager.GetString("Display_back2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] Yes.
        /// </summary>
        internal static string Display_opt1 {
            get {
                return ResourceManager.GetString("Display_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to see all prepared saves ?.
        /// </summary>
        internal static string Display_question {
            get {
                return ResourceManager.GetString("Display_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =========================================================.
        /// </summary>
        internal static string Divider {
            get {
                return ResourceManager.GetString("Divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spanish.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italian.
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong input, return to previous language.
        /// </summary>
        internal static string Lang_error {
            get {
                return ResourceManager.GetString("Lang_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] Français.
        /// </summary>
        internal static string Lang_opt1 {
            get {
                return ResourceManager.GetString("Lang_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] English.
        /// </summary>
        internal static string Lang_opt2 {
            get {
                return ResourceManager.GetString("Lang_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [3] Español.
        /// </summary>
        internal static string Lang_opt3 {
            get {
                return ResourceManager.GetString("Lang_opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [4] Deutsch.
        /// </summary>
        internal static string Lang_opt4 {
            get {
                return ResourceManager.GetString("Lang_opt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [5] Italiano.
        /// </summary>
        internal static string Lang_opt5 {
            get {
                return ResourceManager.GetString("Lang_opt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In which language do you want to pass your application?.
        /// </summary>
        internal static string Lang_question {
            get {
                return ResourceManager.GetString("Lang_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The language used will now be.
        /// </summary>
        internal static string Lang_used {
            get {
                return ResourceManager.GetString("Lang_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong entry.
        /// </summary>
        internal static string Main_error {
            get {
                return ResourceManager.GetString("Main_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closing the software.
        /// </summary>
        internal static string Main_exit {
            get {
                return ResourceManager.GetString("Main_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] Prepare a backup.
        /// </summary>
        internal static string Main_opt1 {
            get {
                return ResourceManager.GetString("Main_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] Run one or more backups.
        /// </summary>
        internal static string Main_opt2 {
            get {
                return ResourceManager.GetString("Main_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [3] Display all saves informations.
        /// </summary>
        internal static string Main_opt3 {
            get {
                return ResourceManager.GetString("Main_opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [4] Settings.
        /// </summary>
        internal static string Main_opt4 {
            get {
                return ResourceManager.GetString("Main_opt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [5] Quit the software.
        /// </summary>
        internal static string Main_opt5 {
            get {
                return ResourceManager.GetString("Main_opt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What do you want to do ?.
        /// </summary>
        internal static string Main_question {
            get {
                return ResourceManager.GetString("Main_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chosed to cancel and go back to the main menu..
        /// </summary>
        internal static string Prepare_back {
            get {
                return ResourceManager.GetString("Prepare_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [] Leave empty to cancel and go back to the main menu.
        /// </summary>
        internal static string Prepare_back2 {
            get {
                return ResourceManager.GetString("Prepare_back2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chosed to do a Differential Save..
        /// </summary>
        internal static string Prepare_diff {
            get {
                return ResourceManager.GetString("Prepare_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [D] Default location.
        /// </summary>
        internal static string Prepare_diff2 {
            get {
                return ResourceManager.GetString("Prepare_diff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  prepared !.
        /// </summary>
        internal static string Prepare_done {
            get {
                return ResourceManager.GetString("Prepare_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect Entry..
        /// </summary>
        internal static string Prepare_error {
            get {
                return ResourceManager.GetString("Prepare_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From :.
        /// </summary>
        internal static string Prepare_from {
            get {
                return ResourceManager.GetString("Prepare_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chosed to do a Full Save..
        /// </summary>
        internal static string Prepare_full {
            get {
                return ResourceManager.GetString("Prepare_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential Copy.
        /// </summary>
        internal static string Prepare_info_diff {
            get {
                return ResourceManager.GetString("Prepare_info_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full Copy.
        /// </summary>
        internal static string Prepare_info_full {
            get {
                return ResourceManager.GetString("Prepare_info_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] Full Save.
        /// </summary>
        internal static string Prepare_opt1 {
            get {
                return ResourceManager.GetString("Prepare_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] Differential Save.
        /// </summary>
        internal static string Prepare_opt2 {
            get {
                return ResourceManager.GetString("Prepare_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [3] Cancel and go back to the main menu.
        /// </summary>
        internal static string Prepare_opt3 {
            get {
                return ResourceManager.GetString("Prepare_opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which type of save do you want to do ?.
        /// </summary>
        internal static string Prepare_question {
            get {
                return ResourceManager.GetString("Prepare_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type the address of the source to save :.
        /// </summary>
        internal static string Prepare_source {
            get {
                return ResourceManager.GetString("Prepare_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type the destination address where the save is going to be located :.
        /// </summary>
        internal static string Prepare_target {
            get {
                return ResourceManager.GetString("Prepare_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To :.
        /// </summary>
        internal static string Prepare_to {
            get {
                return ResourceManager.GetString("Prepare_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing.
        /// </summary>
        internal static string Prepare_working {
            get {
                return ResourceManager.GetString("Prepare_working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have chosen to perform all backups..
        /// </summary>
        internal static string Save_all {
            get {
                return ResourceManager.GetString("Save_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [] Leave blank to cancel and return to main menu.
        /// </summary>
        internal static string Save_back {
            get {
                return ResourceManager.GetString("Save_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have chosen to cancel and return to the main menu..
        /// </summary>
        internal static string Save_back2 {
            get {
                return ResourceManager.GetString("Save_back2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect entry..
        /// </summary>
        internal static string Save_error {
            get {
                return ResourceManager.GetString("Save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The backup.
        /// </summary>
        internal static string Save_exec1 {
            get {
                return ResourceManager.GetString("Save_exec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à will run.
        /// </summary>
        internal static string Save_exec2 {
            get {
                return ResourceManager.GetString("Save_exec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] Single slot save.
        /// </summary>
        internal static string Save_opt1 {
            get {
                return ResourceManager.GetString("Save_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] Sequence of save slots (ex : saves 3 to 7).
        /// </summary>
        internal static string Save_opt2 {
            get {
                return ResourceManager.GetString("Save_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [3] All save slots.
        /// </summary>
        internal static string Save_opt3 {
            get {
                return ResourceManager.GetString("Save_opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to back up, or back up to all locations?.
        /// </summary>
        internal static string Save_question {
            get {
                return ResourceManager.GetString("Save_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The save sequence is going to be executed from saves.
        /// </summary>
        internal static string Save_sequence_exec1 {
            get {
                return ResourceManager.GetString("Save_sequence_exec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to.
        /// </summary>
        internal static string Save_sequence_exec2 {
            get {
                return ResourceManager.GetString("Save_sequence_exec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chose to do a sequence of saves (ex : saves 3 to 7)..
        /// </summary>
        internal static string Save_sequence1 {
            get {
                return ResourceManager.GetString("Save_sequence1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is the first boundary of the sequence to be saved ? (ex :  lower or upper bound).
        /// </summary>
        internal static string Save_sequence2 {
            get {
                return ResourceManager.GetString("Save_sequence2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is the second boundary of the sequence to be saved ? (ex : lower or upper bound).
        /// </summary>
        internal static string Save_sequence3 {
            get {
                return ResourceManager.GetString("Save_sequence3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have chosen to make a backup..
        /// </summary>
        internal static string Save_single {
            get {
                return ResourceManager.GetString("Save_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [0;{0}] Choose a save location between 0 and {0}.
        /// </summary>
        internal static string Save_single_opt1 {
            get {
                return ResourceManager.GetString("Save_single_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What backup do you want to run?.
        /// </summary>
        internal static string Save_single_question {
            get {
                return ResourceManager.GetString("Save_single_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [] Leave blank to cancel and return to main menu.
        /// </summary>
        internal static string Settings_back {
            get {
                return ResourceManager.GetString("Settings_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] Change software language.
        /// </summary>
        internal static string Settings_opt1 {
            get {
                return ResourceManager.GetString("Settings_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] Change default app files location.
        /// </summary>
        internal static string Settings_opt2 {
            get {
                return ResourceManager.GetString("Settings_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [3] Change default log file type.
        /// </summary>
        internal static string Settings_opt3 {
            get {
                return ResourceManager.GetString("Settings_opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings :.
        /// </summary>
        internal static string Settings_question {
            get {
                return ResourceManager.GetString("Settings_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome on Easy save, your backup software !.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
